version: '3.0'

services:
  keycloak_db:
      image: postgres:14.1
      container_name: keycloak_db
      restart: ${RESTART_POLICY}
      volumes:
        - ${KC_DB_DATA_VOLUME}:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${KC_DB_NAME}
        POSTGRES_USER: ${KC_DB_USER}
        POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
  keycloak:
      image: ${KC_IMAGE}
      container_name: keycloak
      restart: ${RESTART_POLICY}
      command: start-dev
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak_postgres
        DB_DATABASE: ${KC_DB_NAME}
        DB_USER: ${KC_DB_USER}
        DB_SCHEMA: public
        DB_PASSWORD: ${KC_DB_PASSWORD}
        KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
        KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
        PROXY_ADDRESS_FORWARDING: ${KC_PROXY_ADDRESS_FORWARDING}
        KC_HOSTNAME_PATH: ${KC_HOSTNAME_PATH}
        KC_PROXY: edge
      ports:
        - ${KC_PORT}:8080
      depends_on:
        - keycloak_db
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true