services:
  keycloak_db:
      image: postgres:14.1
      container_name: keycloak_db
      restart: ${RESTART_POLICY}
      volumes:
        - ${KC_DB_DATA_VOLUME}:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${KC_DB_NAME}
        POSTGRES_USER: ${KC_DB_USER}
        POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      ports:
        - 5432
  keycloak:
      image: ${KC_IMAGE}
      container_name: keycloak
      restart: ${RESTART_POLICY}
      command: start-dev
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: keycloak_db
        KC_DB_URL_PORT: 5432
        KC_DB_URL_DATABASE: ${KC_DB_NAME}
        KC_DB_USERNAME: ${KC_DB_USER}
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: ${KC_DB_PASSWORD}
        KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
        KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
        PROXY_ADDRESS_FORWARDING: ${KC_PROXY_ADDRESS_FORWARDING}
        KC_PROXY: ${KC_PROXY}
        KC_HOSTNAME_PATH: ${KC_HOSTNAME_PATH}
        KC_HOSTNAME_ADMIN_URL: ${KC_HOSTNAME_ADMIN_URL}
        KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}
      ports:
        - ${KC_PORT}:8080
      depends_on:
        - keycloak_db
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true